import Head from "next/head";
import Sidebar from "../components/Sidebar";
import About from "../components/About";
import Experience from "../components/Experience";
import Education from "../components/Education";
import Skills from "../components/Skills";
import Interests from "../components/Interests";
import Awards from "../components/Awards";

export default function Home() {
  return (
    <div>
      {/* <div style={{ display: "grid", gridTemplateColumns: "20% 1fr" }}> */}
      <Head>
        <title>Resume - Theme Preview - Start Bootstrap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div style={{ marginLeft: "17rem" }}>
        <section id="about">
          <About />
        </section>
        <section id="experience">
          <Experience />
        </section>
        <section id="education">
          <Education />
        </section>
        <section id="skills">
          <Skills />
        </section>
        <section id="interests">
          <Interests />
        </section>
        <section id="awards">
          <Awards />
        </section>
      </div>
    </div>
  );
}
